/**
 * Shared types for cryptographic proofs.
 *
 * Supported proof protocols:
 *   - "SP1-Groth16"  — purchase-intent proofs generated by the SP1 ZK circuit
 *   - "Reclaim"      — ZK-TLS web proofs verified via the Reclaim protocol
 *   - generic         — any other agent-submitted proof
 */

/** A single cryptographic proof summary (from attestation service or WebSocket) */
export interface CryptographicProof {
  tool_name: string;
  timestamp: number;
  proof_id?: string;
  verified: boolean;
  onchain_compatible: boolean;
  sequence?: number;
  related_proof_id?: string;
  workflow_stage?: string;
  submitted_by?: string;
  /** Full proof data (when fetched via API) */
  request?: unknown;
  response?: unknown;
  /** Raw proof object (SP1 groth16 bytes, Reclaim onchainProof, etc.) */
  proof?: unknown;
  /** Human-readable response subset for display (may differ from raw response) */
  display_response?: unknown;
  session_id?: string;
}

/** Full proof data returned by the attestation service verify endpoint */
export interface FullProofData {
  proof_id: string;
  session_id: string;
  tool_name: string;
  timestamp: number;
  request: unknown;
  response: unknown;
  /** Human-readable response subset for display */
  display_response?: unknown;
  /**
   * Raw proof object — shape varies by protocol:
   *   SP1-Groth16 : { groth16_proof, public_values, ... }
   *   Reclaim      : { onchainProof: { claimInfo, signedClaim }, ... }
   */
  proof: {
    /** Reclaim ZK-TLS on-chain proof (present for Reclaim protocol) */
    onchainProof?: {
      claimInfo?: {
        provider: string;
        parameters: string;
        context: string;
      };
      signedClaim?: {
        claim: {
          identifier: string;
          owner: string;
          timestampS: number;
          epoch: number;
        };
        signatures: string[];
      };
    };
    [key: string]: unknown;
  };
  verified: boolean;
  onchain_compatible: boolean;
  submitted_by?: string;
  sequence?: number;
  related_proof_id?: string;
  workflow_stage?: string;
  verification_info?: {
    /** e.g. "SP1-Groth16", "Reclaim" */
    protocol: string;
    issuer: string;
    timestamp_verified: boolean;
    signature_algorithm: string;
    can_verify_onchain: boolean;
    reclaim_documentation?: string;
  };
}
